countries = {
    'United States of America': 'us',
    'Russia': 'ru',
    'India': 'in',
    'China': 'cn',
    'Japan': 'jp',
    'South Korea': 'kr',
    'Indonesia': 'id',
    'Australia': 'au',
    'Saudi Arabia': 'sa',
    'United Kingdom': 'gb',
    'France': 'fr',
    'Brazil': 'br',
    'Norway': 'no',
    'Nigeria': 'ng',
    'South Africa': 'za',
    'Egypt': 'eg',
    'New Zealand': 'nz',
    'Philippines': 'ph',
    'Malaysia': 'my'
}
